#!/bin/bash
# ──────────────────────────────────────────────────────────────────────
# PreToolUse hook: Enforce path ownership per worker type.
#
# Reads AGENT_WORKER_TYPE env var (set by worker at startup) and
# checks whether the file being written is within the worker's
# allowed paths as defined in config/generated/hooks-config.json
# (generated by agent-compiler-maven-plugin from agent manifests).
#
# Exit codes:
#   0 — allowed
#   2 — blocked (tool call will be rejected by Claude Code)
# ──────────────────────────────────────────────────────────────────────
set -euo pipefail

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.content // empty')
WORKER_TYPE="${AGENT_WORKER_TYPE:-}"

# If no worker type is set, we're running in human/dev mode — allow everything
if [[ -z "$WORKER_TYPE" ]]; then
  exit 0
fi

# If no file path extracted, allow (non-file tool call)
if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

# Normalize to relative path from project root
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
REL_PATH="${FILE_PATH#"$PROJECT_DIR"/}"

HOOKS_CONFIG="$PROJECT_DIR/config/generated/hooks-config.json"

# Primary: read from generated hooks-config.json (requires only jq)
if [[ -f "$HOOKS_CONFIG" ]]; then
  PATHS=$(jq -r \
    --arg wt "$WORKER_TYPE" \
    '.workerTypes[$wt].ownsPaths // empty | .[]' \
    "$HOOKS_CONFIG" 2>/dev/null)

  if [[ -z "$PATHS" ]]; then
    echo "No ownership paths found for worker '$WORKER_TYPE' in hooks-config — blocking write to '$REL_PATH'" >&2
    exit 2
  fi

  while IFS= read -r prefix; do
    if [[ "$REL_PATH" == "$prefix"* ]]; then
      exit 0
    fi
  done <<< "$PATHS"

  echo "Worker '$WORKER_TYPE' is not allowed to write to '$REL_PATH'. Allowed paths: $(echo $PATHS | tr '\n' ' ')" >&2
  exit 2
fi

echo "No hooks-config.json found — blocking write to '$REL_PATH' for worker '$WORKER_TYPE'" >&2
exit 2