#!/bin/bash
# ──────────────────────────────────────────────────────────────────────
# PreToolUse hook: Enforce MCP tool allowlist per worker type.
#
# Each worker type has a list of allowed MCP server prefixes defined
# in config/generated/hooks-config.json (generated by agent-compiler-maven-plugin
# from agent manifests). Falls back to agent-registry.yml via yq if the
# generated config is not yet available.
#
# Requires: jq (yq optional for fallback)
#
# Exit codes:
#   0 — allowed
#   2 — blocked
# ──────────────────────────────────────────────────────────────────────
set -euo pipefail

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')
WORKER_TYPE="${AGENT_WORKER_TYPE:-}"

# If no worker type set, we're in human/dev mode — allow everything
if [[ -z "$WORKER_TYPE" ]]; then
  exit 0
fi

# If no tool name extracted, allow
if [[ -z "$TOOL_NAME" ]]; then
  exit 0
fi

# Extract MCP server prefix from tool name
# Pattern: mcp__{server}__{tool} → extract {server}
MCP_SERVER=$(echo "$TOOL_NAME" | sed -n 's/^mcp__\([^_]*\)__.*$/\1/p')

# Not an MCP tool — allow (this hook only gates MCP tools)
if [[ -z "$MCP_SERVER" ]]; then
  exit 0
fi

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
HOOKS_CONFIG="$PROJECT_DIR/config/generated/hooks-config.json"

# Primary: read from generated hooks-config.json (requires only jq, no yq)
if [[ -f "$HOOKS_CONFIG" ]]; then
  ALLOWED=$(jq -r \
    --arg wt "$WORKER_TYPE" \
    '.workerTypes[$wt].mcpServers // empty | .[]' \
    "$HOOKS_CONFIG" 2>/dev/null)

  if [[ -z "$ALLOWED" ]]; then
    echo "No MCP allowlist found for worker '$WORKER_TYPE' in hooks-config — blocking '$TOOL_NAME'" >&2
    exit 2
  fi

  if echo "$ALLOWED" | grep -qx "$MCP_SERVER"; then
    exit 0
  fi

  echo "MCP server '$MCP_SERVER' not in allowlist for worker '$WORKER_TYPE'. Allowed: $(echo $ALLOWED | tr '\n' ' ')" >&2
  exit 2
fi

# Fallback: use yq with agent-registry.yml if hooks-config not yet generated
REGISTRY="$PROJECT_DIR/config/agent-registry.yml"
if command -v yq &>/dev/null && [[ -f "$REGISTRY" ]]; then
  REGISTRY_KEY=$(echo "$WORKER_TYPE" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
  ALLOWED=$(yq ".workers.\"$REGISTRY_KEY\".mcpAllowlist[]" "$REGISTRY" 2>/dev/null)

  if [[ -z "$ALLOWED" ]]; then
    echo "No MCP allowlist found for worker '$WORKER_TYPE' in registry — blocking '$TOOL_NAME'" >&2
    exit 2
  fi

  if echo "$ALLOWED" | grep -qx "$MCP_SERVER"; then
    exit 0
  fi

  echo "MCP server '$MCP_SERVER' not in allowlist for worker '$WORKER_TYPE'. Allowed: $(echo $ALLOWED | tr '\n' ' ')" >&2
  exit 2
fi

echo "No hooks-config.json or agent-registry.yml found — blocking MCP tool '$TOOL_NAME' for worker '$WORKER_TYPE'" >&2
exit 2