#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────
# PreToolUse hook: Restrict built-in Claude Code tools per worker type.
#
# Data-driven from config/generated/hooks-config.json (generated by
# agent-compiler-maven-plugin from agent manifests).
#
# If hooks-config.json contains a non-empty "builtinTools" array for the
# worker type, only those tools are permitted. If the field is empty or
# absent, all built-in tools are allowed (open policy for that type).
#
# MCP tools (mcp__*) are skipped — handled by enforce-mcp-allowlist.sh.
# Human/dev sessions (no AGENT_WORKER_TYPE) are always allowed.
#
# Defense-in-depth: mirrors ToolAllowlist.Explicit in Java/Spring AI layer.
#
# Exit codes:
#   0 — allowed
#   2 — blocked
# ──────────────────────────────────────────────────────────────────────
set -uo pipefail

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // "unknown"')
WORKER_TYPE="${AGENT_WORKER_TYPE:-}"

# Human/dev mode — allow everything
if [[ -z "$WORKER_TYPE" ]]; then
    exit 0
fi

# Skip MCP tools — handled by enforce-mcp-allowlist.sh
if [[ "$TOOL_NAME" == mcp__* ]]; then
    exit 0
fi

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(pwd)}"
HOOKS_CONFIG="$PROJECT_DIR/config/generated/hooks-config.json"

if [[ ! -f "$HOOKS_CONFIG" ]]; then
    echo "No hooks-config.json found — blocking '$TOOL_NAME' for worker '$WORKER_TYPE'" >&2
    exit 2
fi

# Read builtinTools array for this worker type
ALLOWED=$(jq -r \
    --arg wt "$WORKER_TYPE" \
    '.workerTypes[$wt].builtinTools // empty | .[]' \
    "$HOOKS_CONFIG" 2>/dev/null)

# If no builtinTools defined (empty array or field absent), allow all built-in tools
if [[ -z "$ALLOWED" ]]; then
    exit 0
fi

# Check if the tool is in the allowlist
if echo "$ALLOWED" | grep -qx "$TOOL_NAME"; then
    exit 0
fi

echo "Tool '$TOOL_NAME' not in builtinTools for worker '$WORKER_TYPE'. Allowed: $(echo "$ALLOWED" | tr '\n' ' ')" >&2
exit 2
