package com.agentframework.rag.model;

/**
 * A chunk of code or documentation ready for embedding.
 *
 * @param content       the chunk text content
 * @param contextPrefix contextual prefix generated by ContextualEnricher (50-100 tokens, nullable)
 * @param metadata      associated metadata (file path, language, entities, ...)
 */
public record CodeChunk(
        String content,
        String contextPrefix,
        ChunkMetadata metadata
) {
    /** Content with contextual prefix prepended (for embedding). */
    public String enrichedContent() {
        if (contextPrefix == null || contextPrefix.isBlank()) {
            return content;
        }
        return contextPrefix + "\n\n" + content;
    }
}
