package com.agentframework.compiler;

import com.agentframework.compiler.manifest.AgentManifest;
import com.agentframework.compiler.manifest.ManifestLoader;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

/**
 * Generates {@code config/worker-profiles.yml}, {@code config/agent-registry.yml},
 * and {@code config/generated/hooks-config.json} from agent manifests — making
 * the manifests the single source of truth.
 */
@Mojo(name = "generate-registry", defaultPhase = LifecyclePhase.GENERATE_RESOURCES)
public class GenerateRegistryMojo extends AbstractMojo {

    @Parameter(property = "agentCompiler.manifestDirectory",
               defaultValue = "${project.basedir}/agents/manifests",
               required = true)
    private String manifestDirectory;

    @Parameter(property = "agentCompiler.configDirectory",
               defaultValue = "${project.basedir}/config",
               required = true)
    private String configDirectory;

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        Path manifestDir = Path.of(manifestDirectory);
        Path configDir = Path.of(configDirectory);

        ManifestLoader loader = new ManifestLoader();

        try {
            List<AgentManifest> manifests = loader.loadAll(manifestDir);
            Files.createDirectories(configDir);

            generateWorkerProfiles(manifests, configDir.resolve("worker-profiles.yml"));
            generateAgentRegistry(manifests, configDir.resolve("agent-registry.yml"));

            Path generatedDir = configDir.resolve("generated");
            Files.createDirectories(generatedDir);
            generateHooksConfig(manifests, generatedDir.resolve("hooks-config.json"));

            getLog().info("Agent Compiler: generated registry files from "
                + manifests.size() + " manifest(s).");

        } catch (ManifestLoader.ManifestValidationException e) {
            throw new MojoFailureException("Manifest validation failed: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new MojoExecutionException("Failed to generate registry: " + e.getMessage(), e);
        }
    }

    private void generateWorkerProfiles(List<AgentManifest> manifests, Path outputFile)
            throws IOException {

        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by agent-compiler-maven-plugin. DO NOT EDIT.\n");
        sb.append("# Source of truth: agents/manifests/*.agent.yml\n\n");
        sb.append("worker-profiles:\n");

        // Profile entries
        for (AgentManifest m : manifests) {
            var spec = m.getSpec();
            if (spec.getWorkerProfile() == null) continue;

            sb.append("  ").append(spec.getWorkerProfile()).append(":\n");
            sb.append("    workerType: ").append(spec.getWorkerType()).append("\n");
            sb.append("    topic: ").append(spec.getTopic()).append("\n");
            sb.append("    subscription: ").append(spec.getSubscription()).append("\n");
            String displayName = m.getMetadata().getDisplayName() != null
                    ? m.getMetadata().getDisplayName()
                    : m.getMetadata().getName();
            sb.append("    displayName: \"").append(displayName).append("\"\n");
            // Capability fields for Specification pattern validation
            var mcpServers = spec.getTools().getMcpServers();
            if (!mcpServers.isEmpty()) {
                sb.append("    mcpServers:\n");
                for (String s : mcpServers) {
                    sb.append("      - ").append(s).append("\n");
                }
            }
            var ownership = spec.getOwnership();
            if (ownership != null && ownership.getOwnsPaths() != null && !ownership.getOwnsPaths().isEmpty()) {
                sb.append("    ownsPaths:\n");
                for (String p : ownership.getOwnsPaths()) {
                    sb.append("      - ").append(p).append("\n");
                }
                // Auto-add worker's own module directory
                sb.append("      - execution-plane/workers/").append(m.getMetadata().getName()).append("/\n");
            }
            sb.append("\n");
        }

        // Defaults section
        sb.append("defaults:\n");
        appendDefault(sb, manifests, "BE", "be-java");
        appendDefault(sb, manifests, "FE", "fe-react");
        appendDefault(sb, manifests, "AI_TASK", null);
        appendDefault(sb, manifests, "CONTRACT", null);
        appendDefault(sb, manifests, "REVIEW", null);

        Files.writeString(outputFile, sb.toString());
        getLog().info("  Generated: " + outputFile);
    }

    private void appendDefault(StringBuilder sb, List<AgentManifest> manifests,
                                String workerType, String defaultProfile) {
        boolean hasProfile = manifests.stream()
            .anyMatch(m -> workerType.equals(m.getSpec().getWorkerType())
                        && m.getSpec().getWorkerProfile() != null);

        if (hasProfile && defaultProfile != null) {
            sb.append("  ").append(workerType).append(": ").append(defaultProfile).append("\n");
        } else {
            sb.append("  ").append(workerType).append(": ~\n");
        }
    }

    private void generateAgentRegistry(List<AgentManifest> manifests, Path outputFile)
            throws IOException {

        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by agent-compiler-maven-plugin. DO NOT EDIT.\n");
        sb.append("# Source of truth: agents/manifests/*.agent.yml\n\n");
        sb.append("workers:\n");

        for (AgentManifest m : manifests) {
            var meta = m.getMetadata();
            var spec = m.getSpec();

            sb.append("\n  ").append(meta.getName()).append(":\n");

            String displayName = meta.getDisplayName() != null ? meta.getDisplayName() : meta.getName();
            sb.append("    displayName: ").append(displayName).append("\n");

            if (spec.getWorkerProfile() != null) {
                sb.append("    workerProfile: ").append(spec.getWorkerProfile()).append("\n");
            }

            sb.append("    topic: ").append(spec.getTopic()).append("\n");
            sb.append("    subscription: ").append(spec.getSubscription()).append("\n");
            sb.append("    image: agent-framework/").append(meta.getName()).append(":latest\n");

            if (meta.getDescription() != null) {
                sb.append("    description: >-\n");
                sb.append("      ").append(meta.getDescription().trim()).append("\n");
            }

            sb.append("    mcpAllowlist:\n");
            for (String tool : spec.getTools().getAllowlist()) {
                sb.append("      - ").append(tool).append("\n");
            }

            var concurrency = spec.getConcurrency();
            int maxConcurrent = concurrency != null ? concurrency.getMaxConcurrentCalls() : 3;
            sb.append("    maxConcurrentCalls: ").append(maxConcurrent).append("\n");

            var prompts = spec.getPrompts();
            if (prompts.getSkills() != null && !prompts.getSkills().isEmpty()) {
                sb.append("    skillPaths:\n");
                for (String skill : prompts.getSkills()) {
                    sb.append("      - ").append(skill).append("\n");
                }
            }

            var ownership = spec.getOwnership();
            if (ownership != null) {
                if (ownership.getOwnsPaths() != null) {
                    sb.append("    ownsPaths:\n");
                    if (ownership.getOwnsPaths().isEmpty()) {
                        sb.append("      []\n");
                    } else {
                        for (String p : ownership.getOwnsPaths()) {
                            sb.append("      - ").append(p).append("\n");
                        }
                    }
                }
            }
        }

        Files.writeString(outputFile, sb.toString());
        getLog().info("  Generated: " + outputFile);
    }

    /**
     * Generates {@code config/generated/hooks-config.json} — a lightweight JSON file
     * consumed by Claude Code hook scripts ({@code enforce-mcp-allowlist.sh} and
     * {@code enforce-ownership.sh}) to replace hardcoded fallback data.
     *
     * <p>Groups manifests by {@code workerType} and merges {@code mcpServers} and
     * {@code ownsPaths} across all workers of the same type. Each worker's own module
     * directory ({@code execution-plane/workers/{name}/}) is auto-added to ownsPaths.</p>
     */
    private void generateHooksConfig(List<AgentManifest> manifests, Path outputFile)
            throws IOException {

        // Group manifests by workerType
        Map<String, List<AgentManifest>> byType = new LinkedHashMap<>();
        for (AgentManifest m : manifests) {
            byType.computeIfAbsent(m.getSpec().getWorkerType(), k -> new ArrayList<>()).add(m);
        }

        StringBuilder json = new StringBuilder();
        json.append("{\n");
        json.append("  \"_comment\": \"Generated by agent-compiler-maven-plugin. DO NOT EDIT.\",\n");
        json.append("  \"workerTypes\": {\n");

        var typeIterator = byType.entrySet().iterator();
        while (typeIterator.hasNext()) {
            var entry = typeIterator.next();
            String workerType = entry.getKey();
            List<AgentManifest> workers = entry.getValue();

            // Merge mcpServers (deduplicated, sorted)
            Set<String> mcpServers = new TreeSet<>();
            for (AgentManifest m : workers) {
                mcpServers.addAll(m.getSpec().getTools().getMcpServers());
            }

            // Merge ownsPaths (deduplicated, sorted) + auto-add worker module dirs
            Set<String> ownsPaths = new TreeSet<>();
            for (AgentManifest m : workers) {
                var ownership = m.getSpec().getOwnership();
                if (ownership != null && ownership.getOwnsPaths() != null) {
                    ownsPaths.addAll(ownership.getOwnsPaths());
                }
                // Auto-add the worker's own module directory
                ownsPaths.add("execution-plane/workers/" + m.getMetadata().getName() + "/");
            }

            json.append("    \"").append(workerType).append("\": {\n");
            json.append("      \"mcpServers\": ").append(toJsonArray(mcpServers)).append(",\n");
            json.append("      \"ownsPaths\": ").append(toJsonArray(ownsPaths)).append("\n");
            json.append("    }");
            if (typeIterator.hasNext()) {
                json.append(",");
            }
            json.append("\n");
        }

        json.append("  }\n");
        json.append("}\n");

        Files.writeString(outputFile, json.toString());
        getLog().info("  Generated: " + outputFile);
    }

    private static String toJsonArray(Collection<String> items) {
        if (items.isEmpty()) return "[]";
        StringJoiner sj = new StringJoiner(", ", "[", "]");
        for (String item : items) {
            sj.add("\"" + item + "\"");
        }
        return sj.toString();
    }
}
