package com.agentframework.orchestrator.reward;

import jakarta.persistence.*;
import java.time.Instant;
import java.util.UUID;

/**
 * A single DPO (Direct Preference Optimization) preference pair.
 *
 * <p>Captures two contrasting outcomes for the same task type — one preferred
 * (higher reward) and one rejected (lower reward). Used to fine-tune LLM agents
 * via preference learning without requiring human labelling.</p>
 *
 * <p>Generated by {@link PreferencePairGenerator} using three strategies:
 * <ol>
 *   <li>{@code same_plan_cross_profile} — two profiles competing on identical workerType within a plan</li>
 *   <li>{@code retry_comparison} — first (failed) vs subsequent (successful) dispatch of the same item</li>
 *   <li>{@code gp_residual_surprise} — cross-profile pairs filtered by GP residual (informative surprises)</li>
 * </ol>
 * </p>
 */
@Entity
@Table(name = "preference_pairs",
       indexes = {
           @Index(name = "idx_pp_worker_type", columnList = "worker_type"),
           @Index(name = "idx_pp_delta",       columnList = "delta_reward DESC"),
           @Index(name = "idx_pp_plan_id",     columnList = "plan_id")
       })
public class PreferencePair {

    @Id
    private UUID id;

    @Column(name = "plan_id")
    private UUID planId;

    @Column(name = "task_key", nullable = false, length = 20)
    private String taskKey;

    @Column(name = "worker_type", nullable = false, length = 20)
    private String workerType;

    /** The prompt that was given to the agent: title + description + context JSON. */
    @Column(name = "prompt_text", nullable = false, columnDefinition = "TEXT")
    private String promptText;

    /** The result with higher reward (the chosen / preferred response). */
    @Column(name = "chosen_result", nullable = false, columnDefinition = "TEXT")
    private String chosenResult;

    /** The result with lower reward (the rejected response). */
    @Column(name = "rejected_result", nullable = false, columnDefinition = "TEXT")
    private String rejectedResult;

    @Column(name = "chosen_reward", nullable = false)
    private float chosenReward;

    @Column(name = "rejected_reward", nullable = false)
    private float rejectedReward;

    /** chosenReward - rejectedReward. Only pairs with delta > MIN_DELTA (0.3) are generated. */
    @Column(name = "delta_reward", nullable = false)
    private float deltaReward;

    /** "same_plan_cross_profile", "retry_comparison", or "gp_residual_surprise". */
    @Column(name = "generation_source", length = 50)
    private String generationSource;

    /** GP residual |actual - predicted| for the chosen item. Only set by gp_residual_surprise. */
    @Column(name = "gp_residual")
    private Float gpResidual;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    protected PreferencePair() {}

    public PreferencePair(UUID id, UUID planId, String taskKey, String workerType,
                          String promptText, String chosenResult, String rejectedResult,
                          float chosenReward, float rejectedReward, String generationSource) {
        this.id = id;
        this.planId = planId;
        this.taskKey = taskKey;
        this.workerType = workerType;
        this.promptText = promptText;
        this.chosenResult = chosenResult;
        this.rejectedResult = rejectedResult;
        this.chosenReward = chosenReward;
        this.rejectedReward = rejectedReward;
        this.deltaReward = chosenReward - rejectedReward;
        this.generationSource = generationSource;
        this.createdAt = Instant.now();
    }

    public PreferencePair(UUID id, UUID planId, String taskKey, String workerType,
                          String promptText, String chosenResult, String rejectedResult,
                          float chosenReward, float rejectedReward, String generationSource,
                          Float gpResidual) {
        this(id, planId, taskKey, workerType, promptText, chosenResult, rejectedResult,
             chosenReward, rejectedReward, generationSource);
        this.gpResidual = gpResidual;
    }

    // ── Getters ─────────────────────────────────────────────────────────────

    public UUID getId() { return id; }
    public UUID getPlanId() { return planId; }
    public String getTaskKey() { return taskKey; }
    public String getWorkerType() { return workerType; }
    public String getPromptText() { return promptText; }
    public String getChosenResult() { return chosenResult; }
    public String getRejectedResult() { return rejectedResult; }
    public float getChosenReward() { return chosenReward; }
    public float getRejectedReward() { return rejectedReward; }
    public float getDeltaReward() { return deltaReward; }
    public String getGenerationSource() { return generationSource; }
    public Float getGpResidual() { return gpResidual; }
    public Instant getCreatedAt() { return createdAt; }
}
