package com.agentframework.messaging.inprocess;

import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

/**
 * Enables component scanning of worker packages in consolidated JVM mode.
 *
 * <p>This configuration is imported by {@link InProcessWorkerAutoConfiguration}
 * only when {@code messaging.provider=in-process}. It adds
 * {@code com.agentframework.workers} to the Spring component scan, allowing
 * all {@code @Component} worker beans (generated by agent-compiler) to be
 * discovered and instantiated in the orchestrator's application context.
 *
 * <p>In standalone worker mode (one JVM per worker), this scan is not needed
 * because each worker's {@code @SpringBootApplication} already scans its own package.
 */
@Configuration
@ComponentScan(basePackages = "com.agentframework.workers")
class InProcessWorkerScanConfig {
}
